name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install System Packages
        run: |
          sudo apt update

          sudo apt install -y \
          zip unzip git \
          python3-pip \
          autoconf automake libtool \
          pkg-config cmake \
          libffi-dev libssl-dev \
          zlib1g-dev \
          build-essential \
          ccache

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools

          cd $HOME/android-sdk/cmdline-tools

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip

          unzip commandlinetools-linux-11076708_latest.zip

          mv cmdline-tools latest

      - name: Set Android Environment
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Install Android Build Tools
        run: |
          yes | sdkmanager --licenses

          sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0"

      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Python Packages
        run: |
          pip install cython==0.29.36
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
