name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev \
            cmake libssl-dev

          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36

      - name: Clean old build
        run: |
          rm -rf .buildozer
          rm -rf bin
          mkdir bin

      - name: Build APK
        run: |
          buildozer android release

      - name: Find APK
        run: |
          echo "SEARCHING APK..."
          find . -name "*.apk"

      - name: Copy APK to bin
        run: |
          APK=$(find . -name "*.apk" | head -n 1)
          echo "FOUND: $APK"
          cp "$APK" ./bin/cubefalling-release.apk

      - name: Verify final APK
        run: |
          ls -la bin
          test -f ./bin/cubefalling-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CubeFalling-APK
          path: ./bin/cubefalling-release.apk
